.class public Lcom/inzisoft/izmobilereader/IZMobileReaderCommon;
.super Ljava/lang/Object;
.source "IZMobileReaderCommon.java"


# static fields
.field public static final IZMOBILEREADER_COMMON_CONF_BIZCARD_HANJA_2_HANGUL:I = 0x1389

.field public static final IZMOBILEREADER_COMMON_CONF_IDCARD_TF_TYPE_PRIORITY:I = 0x138b

.field public static final IZMOBILEREADER_COMMON_CONF_PAGEUTIL_DOC_TYPE:I = 0x138a

.field public static final IZMOBILEREADER_COMMON_COUNTRY_AFRICA_KENYA:I = 0x65

.field public static final IZMOBILEREADER_COMMON_COUNTRY_AFRICA_NIGERIA:I = 0x64

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_BANGLADESH:I = 0x12

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_HONGKONG:I = 0xc

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_INDIA:I = 0xf

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_INDONESIA:I = 0xe

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_KOREA:I = 0x0

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_MALAYSIA:I = 0xd

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_PAKISTAN:I = 0x11

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_SINGAPORE:I = 0xb

.field public static final IZMOBILEREADER_COMMON_COUNTRY_ASIA_UAE:I = 0x10

.field public static final IZMOBILEREADER_COMMON_DOMAIN_BIZCARD:I = 0x14

.field public static final IZMOBILEREADER_COMMON_DOMAIN_BIZ_REGI:I = 0x28

.field public static final IZMOBILEREADER_COMMON_DOMAIN_CAR_REGI:I = 0x1e

.field public static final IZMOBILEREADER_COMMON_DOMAIN_ETC_ID:I = 0x3c

.field public static final IZMOBILEREADER_COMMON_DOMAIN_ID:I = 0xa

.field public static final IZMOBILEREADER_COMMON_DOMAIN_ID_ADD_OVERSEA:I = 0xb

.field public static final IZMOBILEREADER_COMMON_DOMAIN_PASSPORT:I = 0x32

.field public static final IZMOBILEREADER_COMMON_DOMAIN_UNKNOWN:I = 0x0

.field public static final IZMOBILEREADER_COMMON_LANGUAGE_CHINESE_A:I = 0x32

.field public static final IZMOBILEREADER_COMMON_LANGUAGE_CHINESE_S:I = 0x33

.field public static final IZMOBILEREADER_COMMON_LANGUAGE_CHINESE_T:I = 0x34

.field public static final IZMOBILEREADER_COMMON_LANGUAGE_JAPANESE:I = 0x3c

.field public static final IZMOBILEREADER_COMMON_LANGUAGE_KOREAN:I = 0x0

.field public static final IZMOBILEREADER_COMMON_LANGUAGE_LATIN:I = 0xa

.field public static final IZMOBILEREADER_COMMON_RECOG_IMAGE_TYPE_ARGB:I = 0x5

.field public static final IZMOBILEREADER_COMMON_RECOG_IMAGE_TYPE_RGB16:I = 0x3

.field public static final IZMOBILEREADER_COMMON_RECOG_IMAGE_TYPE_RGB24:I = 0x4

.field public static final IZMOBILEREADER_COMMON_RECOG_IMAGE_TYPE_RGB8:I = 0x2

.field public static final IZMOBILEREADER_COMMON_RECOG_IMAGE_TYPE_RGBA:I = 0x6

.field public static final IZMOBILEREADER_COMMON_RECOG_IMAGE_TYPE_UNKNOWN:I = 0x0

.field public static final IZMOBILEREADER_COMMON_RECOG_IMAGE_TYPE_YUV:I = 0x1

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_ADDRESS:I = 0xd1

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_COMPANY:I = 0xd0

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_DIVISION:I = 0xcf

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_EMAIL:I = 0xcc

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_FAX:I = 0xca

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_JOBTITLE:I = 0xce

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_MOBILEPHONE:I = 0xcb

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_NAME:I = 0xc8

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_OFFICEPHONE:I = 0xc9

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZCARD_URL:I = 0xcd

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_ADDRESS:I = 0x1cc

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_BIRTH_DATE:I = 0x1b9

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_BIZ_ITEM:I = 0x1e2

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_BIZ_REGI_NUMBER:I = 0x1a4

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_BIZ_TYPE:I = 0x1e1

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_CETI_BIZ_REGI:I = 0x190

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_COMMENCEMENT_DATE:I = 0x1c2

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_COMPANY_NAME:I = 0x1ae

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_HEAD_OFFICE:I = 0x1d6

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_INC_REGI_NUMBER:I = 0x1c3

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_ISSUE_REASON:I = 0x1ea

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_JOINT_OWNER:I = 0x1f4

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_OWNER_NAME:I = 0x1b8

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_SEAL:I = 0x230

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_BIZ_REGI_TYPE_TAXATION:I = 0x19a

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_ADDRESS:I = 0x134

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_BASE_ADDRESS:I = 0x138

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_CAR_ENGINE:I = 0x137

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_CAR_FORM:I = 0x135

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_CAR_MODEL:I = 0x130

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_CAR_NO:I = 0x131

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_CAR_TYPE:I = 0x12e

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_CAR_USE:I = 0x12f

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_CAR_YEAR:I = 0x136

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_DATE:I = 0x12c

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_ID_RRN:I = 0x133

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_NAME:I = 0x132

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_CAR_REGI_REGI_NO:I = 0x12d

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_ADDRESS:I = 0x2c1

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_DATE:I = 0x2bf

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_ISSUEOFFICE:I = 0x2c3

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_NAME:I = 0x2be

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_NAME_KOREAN:I = 0x2c5

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_NATION:I = 0x2c0

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_PHOTO:I = 0x2c2

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_QUALIFICATION:I = 0x2c4

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_RRN:I = 0x2bd

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ETC_ID_TYPE:I = 0x2bc

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_ADDRESS:I = 0x68

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_APTITUDE_DATE_END:I = 0x6c

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_APTITUDE_DATE_START:I = 0x6d

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_DATE:I = 0x67

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_ISSUE_OFFICE:I = 0x6b

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_LICENSE_NO:I = 0x69

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_LICENSE_TYPE:I = 0x6e

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_NAME:I = 0x66

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_PHOTO:I = 0x6a

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_RRN:I = 0x65

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_ID_SECURITY_SERIAL:I = 0x6f

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_MRZ_1ST_ROW:I = 0x26b

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_MRZ_2ND_ROW:I = 0x26c

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_BOUNDARY:I = 0x26d

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_CHECK_SUM_VERIFIED:I = 0x266

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_DATE_OF_BIRTH:I = 0x25f

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_DATE_OF_BIRTH_VERIFIED:I = 0x260

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_EXPIRATION_DATE:I = 0x262

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_EXPIRATION_DATE_VERIFIED:I = 0x263

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_GIVEN_NAME:I = 0x25b

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_ISSUING_COUNTRY:I = 0x259

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_KR_NAME:I = 0x267

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_KR_PASSPORT_NUMBER:I = 0x26a

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_KR_PERSONAL_NUMBER:I = 0x269

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_LAST_NAME:I = 0x25a

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_NATIONALITY:I = 0x25e

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_PASSPORT_NUMBER:I = 0x25c

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_PASSPORT_NUMBER_VERIFIED:I = 0x25d

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_PERSONAL_NUMBER:I = 0x264

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_PERSONAL_NUMBER_VERIFIED:I = 0x265

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_PHOTO:I = 0x268

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_SEX:I = 0x261

.field public static final IZMOBILEREADER_COMMON_RESULT_FIELD_PASSPORT_TYPE:I = 0x258

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_BIZCARD:I = 0x14

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_BIZ_REGI_CORPORATION:I = 0x28

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_BIZ_REGI_GENERAL_PERSON:I = 0x29

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_CAR_REGI:I = 0x1e

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_ETC_ID_ALIEN_CARD:I = 0x3c

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_ETC_ID_COMPATRIOT_CARD:I = 0x3d

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_ETC_ID_HONOREE_CARD:I = 0x3f

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_ETC_ID_RESIDENST_CARD:I = 0x40

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_ETC_ID_WELFARE_CARD:I = 0x3e

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_ID_DRIVING_LICENSE:I = 0xb

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_ID_RESIDENT_OVERSEA:I = 0xc

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_ID_RESIDENT_REGI:I = 0xa

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_PASSPORT:I = 0x32

.field public static final IZMOBILEREADER_COMMON_RESULT_TYPE_UNKNOWN:I = 0x0

.field public static final IZMOBILEREADER_COMMON_SUB_LANG_ALL:I = 0x1f

.field public static final IZMOBILEREADER_COMMON_SUB_LANG_ALPHABET:I = 0x3

.field public static final IZMOBILEREADER_COMMON_SUB_LANG_MAIN:I = 0x10

.field public static final IZMOBILEREADER_COMMON_SUB_LANG_NUMERIC:I = 0x4

.field public static final IZMOBILEREADER_COMMON_SUB_LANG_SYMBOL:I = 0x8


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
